name: GitHub release
on:
  workflow_call:
    inputs:
      tag:
        description: Tag to release
        type: string
        required: false
        default: ${{ github.ref_name }}
jobs:
  release:
    name: Release ${{ inputs.tag }}
    runs-on: ubuntu-22.04
    steps:
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.tag }}" \
            --verify-tag \
            --generate-notes \
            --repo="${GITHUB_REPOSITORY}"
