name: Create release
on:
  workflow_call:
    inputs:
      tag:
        description: Tag to create release for
        type: string
        required: false
        default: ${{ github.ref_name }}
jobs:
  release:
    name: Create release (${{ inputs.tag }})
    runs-on: ubuntu-20.04
    steps:
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${{ inputs.tag }}"
          echo gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
