name: Deploy mkdocs
on:
  workflow_call:
    inputs:
      plugins:
        description: Plugins to install for mkdocs
        type: string
        required: false
        default: mkdocs-literate-nav mkdocs-material mkdocs-minify-plugin mkdocs-git-revision-date-localized-plugin
      params:
        description: Options to 'mkdocs gh-deploy'
        type: string
        required: false
        default: --force --no-history --ignore-version --strict
jobs:
  deploy:
    name: Deploy to gh-pages
    runs-on: ubuntu-20.04
    steps:
      - name: Self check out
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create requirements.txt
        run: |
          mkdir -p .github/workflows/es-progress/.github
          echo mkdocs > .github/workflows/es-progress/.github/requirements.txt
          for plugin in ${{ inputs.plugins }}; do
            echo "${plugin}" >> .github/workflows/es-progress/.github/requirements.txt
          done

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: .github/workflows/es-progress/.github/requirements.txt

      - name: Install mkdocs
        run: pip install -r .github/workflows/es-progress/.github/requirements.txt

      - name: Deploy docs
        run: mkdocs gh-deploy ${{ inputs.params }}
